new configure, deploy and run infrastructure

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,7 +1,6 @@
 version: 2.1
 
 commands:
-
   install_ansible:
     description: Install Ansible
     steps:
@@ -16,15 +15,19 @@ commands:
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
+
       workflow_id:
         default: "${CIRCLE_WORKFLOW_ID:0:7}"
         type: string  
+        
     steps:
       - run:
           name: Destroy environments
           when: on_fail
           command: |
-            
+            # Your code here
+           
+
             aws s3 rm s3://udapeople-<<parameters.workflow_id>> --recursive
             aws cloudformation delete-stack --stack-name "udapeople-backend-<<parameters.workflow_id>>"
             aws cloudformation delete-stack --stack-name "udapeople-frontend-<<parameters.workflow_id>>"
@@ -32,20 +35,24 @@ commands:
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
-      # Add parameter here     
+      # Add parameter here
+      workflow_id:
+        default: "${CIRCLE_WORKFLOW_ID:0:7}"
+        type: string
+         
     steps:
       - run:
           name: Revert migrations
-          # Add when this will run
+          
+          when: on_fail
           command: |
             # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            SUCCESS = 1
+            SUCCESS=$(curl --insecure "https://kvdb.io/RU3Yg3N2gdMc3Pc9ktQy4C/migration_<<parameters.workflow_id>>")
             if(( $SUCCESS==1 )); 
             then
-            #  cd ~/project/backend
-            #  npm install
-            #  Add revert code here. You can find this in the Getting Started section.
-              exit 1
+              cd ~/project/backend
+              npm install
+              npm run migrations:revert
             fi
             
 jobs:
@@ -63,6 +70,7 @@ jobs:
             cd frontend
             npm install
             npm run build
+
       - save_cache:
           paths: [frontend/node_modules]
           key: frontend-build
@@ -81,6 +89,7 @@ jobs:
              cd backend
              npm install
              npm run build
+
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
@@ -90,60 +99,65 @@ jobs:
       # Docker image here
       - image: circleci/node:13.8.0
     steps:
+      # Checkout code from git
       - checkout
       - restore_cache:
           keys: [frontend-build]
       - run:
           name: Run frontend test
           command: |
+            # Your code here
             cd frontend
             npm install
             npm run test
+
       - save_cache:
           paths: [frontend/node_modules]
           key: Run frontend-test
-                
+               
   test-backend:
     docker:
       # Docker image here
-        - image: circleci/node:13.8.0
+      - image: circleci/node:13.8.0
     steps:
+      # Checkout code from git
       - checkout
       - restore_cache:
           keys: [backend-build]
       - run:
           name: Run backend test
           command: |
+            # Your code here
             cd backend
             npm install
+            # npm install oauth-sign@^0.9.0
             npm run test
       - save_cache:
           paths: [backend/node_modules]
-          key: Run backend-test
+          key: backend-test
             
   scan-frontend:
     docker:
       # Docker image here
-       - image: circleci/node:13.8.0
+      - image: circleci/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-build]
+          keys: [scanfrontend-test]
       - run:
-          name: Analyse frontend
+          name: Scan-frontend
           command: |
             cd frontend
-            npm install oauth-sign@^0.9.0
+            npm install
+            # npm install oauth-sign@^0.9.0
             npm audit fix --audit-level=critical --force
-            npm audit fix --audit-level=critical --force
-            npm audit --audit-level=critical
       - save_cache:
           paths: [frontend/node_modules]
           key: scanfrontend-test
 
+
   scan-backend:
     docker:
-      # Docker image here
       - image: circleci/node:13.8.0
     steps:
       - checkout
@@ -160,47 +174,38 @@ jobs:
           paths: [backend/node_modules]
           key: scanbackend-test
 
-
   deploy-infrastructure:
     docker:
       # Docker image here that supports AWS CLI
-      - image: amazon/aws-cli
+     - image: amazon/aws-cli
     steps:
+      # Checkout code from git
       - checkout
       - run:
           name: Install dependencies
           command: |
             yum install -y tar gzip
-      - run: 
+      - run:
           name: Ensure back-end infrastructure exists
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/backend.yml \
-              --tags project=your-tag \
-              --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} \
-              --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7}
+              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
+              --tags project=udapeople
+            
+               
+             
       - run:
           name: Ensure front-end infrastructure exist
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/frontend.yml \
-              --tags project=your-tag \
-              --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7} \
-              --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7}
-      # - run:
-      #     name: Add back-end ip to ansible inventory
-      #     command: |
-      #       echo $(aws ec2 describe-instances \
-      #       --query 'Reservations[*].Instances[*].PublicIpAddress' \
-      #       --filters Name=tag:aws:cloudformation:stack-name,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} \
-      #       --output text) >> ~/project/.circleci/ansible/inventory.txt
-      # - persist_to_workspace:
-      #     root: ~/
-      #     paths:
-      #       - project/.circleci/ansible/inventory.txt
-      # - destroy-environment:
-      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-
+              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
+              --tags project=udapeople
+              
+              
       - run:
           name: Add back-end ip to ansible inventory
           command: |
@@ -223,107 +228,85 @@ jobs:
           paths:
             - project/.circleci/ansible/inventory.txt
       # Here's where you will add some code to rollback on failure      
-configure-infrastructure:
-    docker:
-      # Docker image here that supports Ansible
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - add_ssh_keys:
-          fingerprints:
-            - "88:4a:88:5c:92:9e:3a:37:75:0d:d5:93:1a:c4:04:cd"
-      - attach_workspace:
-          at: ~/
-     
-      - install_ansible
-      # - install_awscli
-      
-      - run:
-          name: Configure server
-          command: |
-            # add environment variables to server
-            echo ENVIRONMENT=production > backend/.env
-            echo TYPEORM_CONNECTION=$TYPEORM_CONNECTION >> backend/.env
-            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> backend/.env
-            echo TYPEORM_ENTITIES=$TYPEORM_ENTITIES >> backend/.env
-            echo TYPEORM_HOST=$TYPEORM_HOST >> backend/.env
-            echo TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS >> backend/.env
-            echo TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR >> backend/.env
-            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> backend/.env
-            echo TYPEORM_PORT=$TYPEORM_PORT >> backend/.env
-            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> backend/.env
-            cat backend/.env
-            
-            cd .circleci/ansible
-            cat inventory.txt
 
-            ansible-playbook -i inventory.txt configure-server.yml
-      - persist_to_workspace:
-          root: ~/
-          paths:
-            - project/backend
-      - destroy-environment
   # configure-infrastructure:
   #   docker:
-  #     - image: python:3.7-alpine3.16
+  #     # Docker image here that supports Ansible
+  #     - image: cimg/base:stable
   #   steps:
   #     - checkout
   #     - add_ssh_keys:
   #         fingerprints:
   #           - "88:4a:88:5c:92:9e:3a:37:75:0d:d5:93:1a:c4:04:cd"
-     
-  #     - run:
-  #         name: Install dependencies
-  #         command: |
-  #           apk add --update --no-cache tar gzip ansible aws-cli
-  #           exit 1
   #     - attach_workspace:
   #         at: ~/
+     
+  #     - install_ansible
+  #     # - install_awscli
+      
   #     - run:
   #         name: Configure server
   #         command: |
+  #           # add environment variables to server
+  #           echo ENVIRONMENT=production > backend/.env
+  #           echo TYPEORM_CONNECTION=$TYPEORM_CONNECTION >> backend/.env
+  #           echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> backend/.env
+  #           echo TYPEORM_ENTITIES=$TYPEORM_ENTITIES >> backend/.env
+  #           echo TYPEORM_HOST=$TYPEORM_HOST >> backend/.env
+  #           echo TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS >> backend/.env
+  #           echo TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR >> backend/.env
+  #           echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> backend/.env
+  #           echo TYPEORM_PORT=$TYPEORM_PORT >> backend/.env
+  #           echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> backend/.env
+  #           cat backend/.env
+            
   #           cd .circleci/ansible
   #           cat inventory.txt
 
   #           ansible-playbook -i inventory.txt configure-server.yml
-  #     - destroy-environment:
-  #         workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-      # Here's where you will add some code to rollback on failure      
-
+  #     - persist_to_workspace:
+  #         root: ~/
+  #         paths:
+  #           - project/backend
+  #     - destroy-environment
+     
   # run-migrations:
   #   docker:
+  #     # Docker image here that supports NodeJS
   #     - image: circleci/node:13.8.0
   #   steps:
   #     - checkout
-  #     - run:
-  #         name: Install dependencies
-  #         command: |
-  #           apk add --update --no-cache tar gzip nodejs npm aws-cli curl
-  #           # curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-  #           # unzip -qq awscliv2.zip
-  #           # sudo ./aws/install
-  #     - restore_cache:
-  #         keys: [backend-build]
-  #     - attach_workspace:
-  #         at: ~/
   #     - run:
   #         name: Run migrations
   #         command: |
   #           cd backend
   #           npm install
-  #           npm run build
-  #           npm run migrations >> migrations.txt
+  #           npm run migrations > migrations_dump.txt
+            
+            
   #     - run:
-  #         name: Send migration results to kvdb
+  #         name: Send migration results to kvdb.io
   #         command: |
   #           if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
   #           then
   #             curl --insecure https://kvdb.io/MjQwMcgGbszGJZAkAzyMSj/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
   #           fi
-
-  #     - destroy-environment:
-  #         workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-         
+  #     - destroy-environment
+  #     - revert-migrations
+          
+    # steps:
+    #   # Checkout code from git
+    #   - run:
+    #       name: Run migrations
+    #       command: |
+    #         # Your code here
+    #         exit 1
+    #   - run:
+    #       name: Send migration results to memstash
+    #       command: |
+    #         # Your code here
+    #         exit 1
+    #  # Here's where you will add some code to rollback on failure      
 
 #   deploy-frontend:
 #     docker:
@@ -436,11 +419,11 @@ workflows:
           requires: [build-frontend]
       - deploy-infrastructure:
           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-      #     filters:
-      #       branches:
-      #         only: [test-feature-branch]
-      - configure-infrastructure:
-          requires: [deploy-infrastructure]
+          filters:
+            branches:
+              only: [master]
+      # - configure-infrastructure:
+      #     requires: [deploy-infrastructure]
       # - run-migrations:
       #     requires: [configure-infrastructure]
       # - deploy-frontend:
